server:
  port: 8084

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

      routes:

        # ================= AUTH SERVICE =================
        - id: auth-service
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        # ================= COURSE SERVICE =================
        - id: course-service
          uri: http://localhost:8081
          predicates:
            - Path=/courses/**
          filters:
            - StripPrefix=1


        # ================= ENROLLMENT SERVICE =================
        - id: enrollment-service
          uri: http://localhost:8082
          predicates:
            - Path=/enrollments/**
          filters:
            - StripPrefix=1


        # ================= STUDENT SERVICE =================
        - id: student-service
          uri: http://localhost:8083
          predicates:
            - Path=/students/**
          filters:
            - StripPrefix=1
