server:
  port: 8084

spring:
  application:
    name: apigateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

      routes:

        # ================= AUTH SERVICE =================
        - id: authservice
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**
         

        # ================= COURSE SERVICE =================
        - id: courseservice
          uri: http://localhost:8081
          predicates:
            - Path=/courses/**
         

        # ================= ENROLLMENT SERVICE =================
        - id: enrollmentservice
          uri: http://localhost:8082
          predicates:
            - Path=/enrollments/**
          

        # ================= STUDENT SERVICE =================
        - id: studentservice
          uri: http://localhost:8083
          predicates:
            - Path=/students/**
          
          eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
