server:
  port: 8080

spring:
  application:
    name: AUTH-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: chauhan123@

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mysecretkey123456789
  expiration: 86400000   # 1 day

  eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
