spring:
  application:
    name: CourseService
  datasource:
    url: jdbc:mysql://localhost:3306/course
    username: root
    password: chauhan123@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081
