server:
  port: 8082

spring:
  application:
    name: ENROLLMENT-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/enrollment
    username: root
    password: chauhan123@

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
