spring:
  application:
    name: StudentService
  datasource:
    url: jdbc:mysql://localhost:3306/student
    username: root
    password: chauhan123@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083

  eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
